# Generated by Django 4.2.27 on 2026-05-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referraltoken',
            new_name='referrals_r_token_1dc47e_idx',
            old_name='referrals_r_token_is_active_idx',
        ),
    ]
