services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - buzzy-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      -  buzzy-project

  web:
    image: buzzy-web:v0.1
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - buzzy-uploads:/buzzy-backend/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env

    networks:
      -  buzzy-project
    depends_on:
      - db

volumes:
  buzzy-db:
  buzzy-uploads:

networks:
  buzzy-project:
    driver: bridge
