# Generated by Django 4.2.27 on 2026-03-29 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=10)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('agora_uid_caller', models.PositiveIntegerField()),
                ('agora_uid_callee', models.PositiveIntegerField()),
                ('allowed_seconds', models.PositiveIntegerField(default=0)),
                ('consumed_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('ended_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('agora_token_expire_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('CALLS', 'Llamadas Mensuales'), ('VIDEO CALLS', 'Videos Llamadas Mensuales'), ('MESSAGES', 'Mensages Mensuales'), ('COMMENTS', 'Comentarios VIP'), ('DESIGNS', 'Nuevo Design Interface'), ('AI_GENERATION', 'Generación de Videos/Imágenes con IA'), ('OTHER', 'Otros beneficios')], max_length=20)),
                ('limit', models.PositiveIntegerField(help_text='0 para ilimitado, o un número específico')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Beneficio de suscripcion',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VIP', 'VIP'), ('PLUS', 'Plus'), ('FRIEND', 'Friend')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('comments_this_month', models.PositiveIntegerField(default=0)),
                ('calls_this_month', models.PositiveIntegerField(default=0)),
                ('video_calls_this_month', models.PositiveIntegerField(default=0)),
                ('voice_seconds_this_month', models.PositiveIntegerField(default=0)),
                ('video_seconds_consumed_this_month', models.PositiveIntegerField(default=0)),
                ('ai_generations_this_month', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
