# Generated by Django 4.2.27 on 2026-03-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='subscriptions.usersubscription'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('subscriber', 'subscribed_to')},
        ),
    ]
