# Generated by Django 4.2.19 on 2026-03-04 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 3, 4, 22, 40, 18, 411587, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
