# Generated by Django 4.2.27 on 2026-04-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbenefit',
            name='benefit_type',
            field=models.CharField(choices=[('CALLS', 'Llamadas Mensuales'), ('VIDEO CALLS', 'Videos Llamadas Mensuales'), ('MESSAGES', 'Mensages Mensuales'), ('COMMENTS', 'Comentarios VIP'), ('DESIGNS', 'Nuevo Design Interface'), ('AI_GENERATION', 'Generación de Videos con IA'), ('AI_GENERATION_IMAGEN', 'Generación de Imágenes con IA'), ('OTHER', 'Otros beneficios')], max_length=20),
        ),
    ]
