# Generated by Django 4.2.19 on 2026-03-11 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_usersubscription_last_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('subscriber', 'subscribed_to')},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
    ]
