# Generated by Django 4.2.27 on 2026-04-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionbenefit_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ai_image_generations_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
