# Generated by Django 4.2.19 on 2026-03-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_subscribed_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('CALLS', 'Llamadas Mensuales'), ('COMMENTS', 'Comentarios VIP')], max_length=20)),
                ('limit', models.PositiveIntegerField(help_text='0 para ilimitado, o un número específico')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='subscriptions.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'benefit_type')},
            },
        ),
    ]
