# Generated by Django 4.2.19 on 2026-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionbenefit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionbenefit',
            options={'verbose_name': 'Beneficio de suscripcion'},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionbenefit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscriptionbenefit',
            name='benefit_type',
            field=models.CharField(choices=[('CALLS', 'Llamadas Mensuales'), ('VIDEO CALLS', 'Videos Llamadas Mensuales'), ('COMMENTS', 'Comentarios VIP'), ('DESIGN', 'Nuevo Design Interface'), ('OTHER', 'Otros beneficios')], max_length=20),
        ),
    ]
