# Generated by Django 4.2.27 on 2026-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_ai_image_generations_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ai_image_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ai_video_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
