# Generated by Django 4.2.27 on 2026-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionbenefit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbenefit',
            name='benefit_type',
            field=models.CharField(choices=[('CALLS', 'Llamadas Mensuales'), ('VIDEO CALLS', 'Videos Llamadas Mensuales'), ('MESSAGES', 'Mensages Mensuales'), ('COMMENTS', 'Comentarios VIP'), ('DESIGNS', 'Nuevo Design Interface'), ('OTHER', 'Otros beneficios')], max_length=20),
        ),
    ]
