# Generated by Django 4.2.27 on 2026-06-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscriptionbenefit_benefit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionbenefit',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Beneficio de suscripcion'},
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la tarjeta del plan (menor = primero).'),
        ),
    ]
