# Generated by Django 4.2.19 on 2026-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Nota de voz'), ('gif', 'GIF'), ('file', 'Archivo'), ('document', 'Documento'), ('contact', 'Contacto'), ('poll', 'Encuesta'), ('event', 'Evento'), ('sticker', 'Sticker')], default='text', max_length=20),
        ),
    ]
