# Generated by Django 4.2.19 on 2026-03-11 18:26

import apps.videos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, unique=True)),
                ('gift_type', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sent_gifts', to='videos.giftstory')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sent_gifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gift_video', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='videos.video')),
            ],
        ),
    ]
