# Generated by Django 4.2.27 on 2026-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_duration_alter_video_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audit_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
