# Generated by Django 4.2.19 on 2026-03-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videogift'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(help_text='Nombre del icono en frontend, ej: ImageIcon', max_length=50)),
                ('color_bg', models.CharField(help_text='Clases CSS para el fondo, ej: bg-blue-500/20', max_length=100)),
                ('color_text', models.CharField(help_text='Clases CSS para el texto, ej: text-blue-400', max_length=100)),
                ('color_border', models.CharField(help_text='Clases CSS para el borde hover, ej: hover:border-blue-500/50', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Style',
                'verbose_name_plural': 'AI Styles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen de ejemplo (thumbnail)', null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='videos.aistyle')),
            ],
            options={
                'verbose_name': 'AI Template',
                'verbose_name_plural': 'AI Templates',
                'ordering': ['style', 'order'],
            },
        ),
    ]
