# Generated by Django 5.1.6 on 2025-02-11 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='videos_cate_name_bcfb98_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='videos_cate_slug_4ff2e4_idx'),
        ),
    ]
