# Generated by Django 4.2.27 on 2026-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('videos_count', models.PositiveIntegerField(default=0, help_text='Videos que incluye el paquete')),
                ('images_count', models.PositiveIntegerField(default=0, help_text='Imágenes que incluye el paquete')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=6)),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar este paquete')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Package',
                'verbose_name_plural': 'AI Packages',
                'ordering': ['order', 'price'],
            },
        ),
    ]
