# Generated by Django 4.2.27 on 2026-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_ai_package_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationhistory',
            name='byteplus_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aigenerationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aigenerationhistory',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
