# Generated by Django 4.2.27 on 2026-03-21 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_aistyle_aitemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('media_url', models.URLField(max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.aistyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Generation History',
                'verbose_name_plural': 'AI Generation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
