# Generated by Django 4.2.19 on 2026-03-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_aigenerationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Imagen')], default='video', max_length=10),
        ),
    ]
