# Generated by Django 4.2.27 on 2026-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_ai_history_status_byteplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_track_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='volume_music',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='video',
            name='volume_original',
            field=models.FloatField(default=1.0),
        ),
    ]
