# Generated by Django 4.2.19 on 2026-03-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.PositiveIntegerField(default=0)),
                ('engagements', models.PositiveIntegerField(default=0)),
                ('valid_views', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Stats',
                'verbose_name_plural': 'Video Stats',
            },
        ),
    ]
