# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_notification_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='folder_type',
            field=models.CharField(choices=[('standard', 'Amigos'), ('request', 'Solicitud de chat'), ('hidden', 'Ocultos')], default='standard', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['folder_type'], name='videos_chat_folder_7e1c2d_idx'),
        ),
    ]
