# Generated by Django 4.2.27 on 2026-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_chatroom_folder_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='videos_chat_folder__fee9ba_idx',
            old_name='videos_chat_folder_7e1c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='videos_noti_recipie_901c94_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='videos_noti_recipie_68d036_idx',
            old_name='notif_recipient_created_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
