# Generated by Django 4.2.27 on 2026-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_rename_videos_chat_folder_7e1c2d_idx_videos_chat_folder__fee9ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='folder_type',
            field=models.CharField(choices=[('standard', 'Amigos'), ('known', 'Conocidos'), ('request', 'Solicitudes'), ('hidden', 'Ocultos')], default='standard', max_length=20),
        ),
    ]
