# Generated by Django 4.2.27 on 2026-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_add_known_folder_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='videos_chat_folder__fee9ba_idx',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='folder_type',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='folder_type_p1',
            field=models.CharField(choices=[('standard', 'Amigos'), ('known', 'Conocidos'), ('request', 'Solicitudes'), ('hidden', 'Ocultos')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='folder_type_p2',
            field=models.CharField(choices=[('standard', 'Amigos'), ('known', 'Conocidos'), ('request', 'Solicitudes'), ('hidden', 'Ocultos')], default='standard', max_length=20),
        ),
    ]
