# Generated by Django 5.1.6 on 2025-02-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reverce', to='videos.video'),
        ),
    ]
