# Generated by Django 5.1.6 on 2025-02-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_view_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comernt_video_reverce', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_video_reverce', to='videos.video'),
        ),
    ]
