# Generated by Django 4.2.27 on 2026-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_per_user_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostats',
            name='monetizable_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
