# Generated by Django 5.1.6 on 2025-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_comment_video_id_alter_like_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes_count',
        ),
    ]
