# Generated by Django 4.2.27 on 2026-04-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_add_monetizable_views_to_videostats'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='comments/audio/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('profile_visit', 'Profile Visit'), ('story_like', 'Story Like'), ('gift', 'Gift'), ('mention', 'Mention'), ('earning', 'Earning')], default='follow', max_length=50),
        ),
    ]
