# Generated by Django 4.2.27 on 2026-04-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_add_audio_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/'),
        ),
    ]
