# Generated by Django 5.1.6 on 2025-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_video_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
