# Generated by Django 4.2.27 on 2026-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_comment_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftstory',
            name='is_premium_exclusive',
            field=models.BooleanField(default=False, help_text='Solo usuarios Buzzy Premium pueden enviar/recibir este regalo'),
        ),
    ]
