# Generated by Django 5.1.6 on 2025-11-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_video_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
