# Generated by Django 5.1.6 on 2025-11-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_video_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liked',
        ),
    ]
