# Generated by Django 5.1.6 on 2025-11-20 01:01

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_remove_video_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True),
        ),
    ]
