# Generated by Django 4.2.27 on 2026-04-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_add_audiotrack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiotrack',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='duration_secs',
            field=models.PositiveIntegerField(default=0, help_text='Duración en segundos'),
        ),
    ]
