# Generated by Django 5.1.6 on 2025-11-20 20:57

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_comment_uuid_like_uuid_video_uuid_view_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True, unique=True),
        ),
    ]
