# Generated by Django 4.2.27 on 2026-04-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_alter_audiotrack_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_trim_start',
            field=models.FloatField(default=0.0),
        ),
    ]
