# Generated by Django 4.2.27 on 2026-05-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_add_audio_trim_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_track_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_track_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_track_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_trim_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_trim_start',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_volume_music',
            field=models.FloatField(default=0.8),
        ),
    ]
