# Generated by Django 5.1.6 on 2025-11-20 21:13

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_alter_video_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, null=True, unique=True),
        ),
    ]
