# Generated by Django 5.1.6 on 2025-11-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_followed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followed',
        ),
    ]
