# Generated by Django 5.1.6 on 2025-11-28 00:32

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_story_storymedia_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymedia',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, unique=True),
        ),
    ]
