# Generated by Django 4.2.27 on 2026-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_add_ai_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='story_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Nota de voz'), ('gif', 'GIF'), ('file', 'Archivo'), ('document', 'Documento'), ('contact', 'Contacto'), ('poll', 'Encuesta'), ('event', 'Evento'), ('sticker', 'Sticker'), ('story_reply', 'Respuesta a historia')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('profile_visit', 'Profile Visit'), ('story_like', 'Story Like'), ('gift', 'Gift'), ('mention', 'Mention'), ('earning', 'Earning'), ('welcome', 'Welcome')], default='follow', max_length=50),
        ),
    ]
