# Generated by Django 4.2.27 on 2026-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_story_reply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
