# Generated by Django 4.2.27 on 2026-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_add_story_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogift',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
