# Generated by Django 5.1.6 on 2025-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_giftstory_storygift'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygift',
            name='gift_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
