# Generated by Django 4.2.27 on 2026-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_usergift'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygift',
            name='vip_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
