# Generated by Django 5.1.6 on 2025-12-02 20:30

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_storygift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygift',
            name='uuid',
            field=models.CharField(blank=True, default=apps.videos.models.full_uuid, max_length=32, unique=True),
        ),
    ]
