# Generated by Django 4.2.27 on 2026-05-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_storygift_vip_message'),
        ('videos', '0029_vip_message_gifts'),
    ]

    operations = [
    ]
