# Generated by Django 5.1.6 on 2025-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_storygift_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftstory',
            name='emoji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
