# Generated by Django 5.1.6 on 2025-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_giftstory_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
