# Generated by Django 5.1.6 on 2025-12-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_storygift_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftstory',
            name='color_premiun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
