# Generated by Django 4.2.27 on 2026-05-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_story_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_trim_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='privacy',
            field=models.CharField(choices=[('public', 'Público'), ('followers', 'Solo seguidores'), ('private', 'Privado')], db_index=True, default='public', max_length=10),
        ),
    ]
