# Generated by Django 4.2.27 on 2026-01-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0037_chatroom_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='initiator',
            field=models.ForeignKey(blank=True, help_text='Usuario que inició la conversación (normalmente quien siguió primero)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
