# Generated by Django 4.2.27 on 2026-06-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_follower_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='privacy',
            field=models.CharField(choices=[('public', 'Público'), ('followers', 'Solo seguidores'), ('subscribers', 'Solo suscriptores'), ('private', 'Privado')], db_index=True, default='public', max_length=20),
        ),
    ]
