# Generated by Django 4.2.27 on 2026-06-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_alter_video_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='privacy',
            field=models.CharField(choices=[('public', 'Público'), ('subscribers', 'Solo suscriptores')], db_index=True, default='public', max_length=20),
        ),
    ]
