# Generated by Django 4.2.27 on 2026-06-12 02:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0041_story_privacy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('user_id', 'video_id')},
        ),
    ]
