# Generated by Django 4.2.27 on 2026-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trending_recentsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pics/avatar.webp', null=True, upload_to='media/profile_pics/'),
        ),
    ]
