# Generated by Django 5.1.6 on 2025-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_country_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/avatar.webp', null=True, upload_to='media/profile_pics/'),
        ),
    ]
