# Generated by Django 4.2.27 on 2026-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_buzzy_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
