# Generated by Django 4.2.19 on 2026-03-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
