# Generated by Django 4.2.27 on 2026-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_socialaccount_followers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_video',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_videos/'),
        ),
    ]
