# Generated by Django 4.2.19 on 2026-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_phone_verified_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
