# Generated by Django 4.2.27 on 2026-03-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_reset_password_code_user_reset_password_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pics/avatar.webp', null=True, upload_to='media/profile_pics/'),
        ),
    ]
