# Generated by Django 4.2.27 on 2026-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/avatar.webp', null=True, upload_to='profile_pics/photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_video',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos/video/'),
        ),
    ]
