# Generated by Django 4.2.27 on 2026-05-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_fcmdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='users_fcmde_user_id_3a5329_idx',
            old_name='users_fcmde_user_id_idx',
        ),
    ]
