# Generated by Django 4.2.27 on 2026-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_users_fcmde_user_id_idx_users_fcmde_user_id_3a5329_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_referral_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
