# Generated by Django 4.2.27 on 2026-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_pending_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_sound_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_sound_gifts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_sound_messages',
            field=models.BooleanField(default=True),
        ),
    ]
