# Generated by Django 4.2.27 on 2026-06-11 21:08

import Buzzy.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_notif_sound_followers_user_notif_sound_gifts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=Buzzy.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='refresh_token',
            field=Buzzy.encrypted_fields.EncryptedTextField(blank=True),
        ),
    ]
