# Generated by Django 4.2.19 on 2026-03-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objective', models.CharField(choices=[('TRAFFIC', 'Traffic'), ('AWARENESS', 'Awareness'), ('SALES', 'Sales'), ('FOLLOWERS', 'Followers')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media_file', models.FileField(upload_to='ads/media/')),
                ('cta_text', models.CharField(choices=[('LEARN_MORE', 'Learn More'), ('SHOP_NOW', 'Shop Now'), ('SIGN_UP', 'Sign Up'), ('CONTACT_US', 'Contact Us'), ('WATCH_VIDEO', 'Watch Video')], default='LEARN_MORE', max_length=20)),
                ('destination_url', models.URLField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative', to='ads.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ads.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(default=18)),
                ('age_max', models.PositiveIntegerField(default=65)),
                ('gender', models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10)),
                ('locations', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('estimated_reach', models.PositiveIntegerField(default=0)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='ads.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ads.adcampaign')),
            ],
            options={
                'verbose_name_plural': 'Ad Analytics',
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
