# Generated by Django 4.2.27 on 2026-03-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative', to='ads.adcampaign'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adbudget',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ads.adcampaign'),
        ),
        migrations.AddField(
            model_name='adaudience',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='ads.adcampaign'),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ads.adcampaign'),
        ),
        migrations.AlterUniqueTogether(
            name='adimpression',
            unique_together={('campaign', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='adanalytics',
            unique_together={('campaign', 'date')},
        ),
    ]
