# Generated by Django 4.2.27 on 2026-04-16 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaudience',
            name='max_frequency',
            field=models.PositiveIntegerField(default=3, help_text='Max times same user sees this ad per day'),
        ),
        migrations.AddField(
            model_name='adbudget',
            name='bidding_model',
            field=models.CharField(choices=[('CPM', 'Cost per 1000 Impressions'), ('CPC', 'Cost per Click')], default='CPM', max_length=10),
        ),
        migrations.AddField(
            model_name='adbudget',
            name='cpc_bid',
            field=models.DecimalField(decimal_places=4, default='0.1000', max_digits=8),
        ),
        migrations.AddField(
            model_name='adbudget',
            name='cpm_bid',
            field=models.DecimalField(decimal_places=4, default='1.4300', max_digits=8),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adaudience',
            name='radius',
            field=models.PositiveIntegerField(default=50, help_text='Search radius in km'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='AdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ads.adcampaign')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Review',
                'verbose_name_plural': 'Ad Reviews',
            },
        ),
        migrations.CreateModel(
            name='AdDailyFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_frequencies', to='ads.adcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_daily_frequencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Daily Frequency',
                'verbose_name_plural': 'Ad Daily Frequencies',
                'unique_together': {('campaign', 'user', 'date')},
            },
        ),
    ]
