# Generated by Django 4.2.27 on 2026-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adimpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbudget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
