# Generated by Django 4.2.19 on 2026-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adbudget_spent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaudience',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaudience',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaudience',
            name='radius',
            field=models.PositiveIntegerField(default=50, help_text='Search radius in kilometers'),
        ),
    ]
