# Generated by Django 4.2.27 on 2026-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adaudience_max_frequency_adbudget_bidding_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpm_rate', models.DecimalField(decimal_places=4, default='1.4300', help_text='$ per 1,000 impressions charged to advertiser', max_digits=8)),
                ('cpc_rate', models.DecimalField(decimal_places=4, default='0.1000', help_text='$ per click charged to advertiser', max_digits=8)),
                ('ctr_estimate', models.DecimalField(decimal_places=4, default='0.0200', help_text='Estimated CTR used for reach projections (e.g. 0.02 = 2%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Ads Config',
                'verbose_name_plural': 'Ads Config',
            },
        ),
    ]
