# Generated by Django 4.2.27 on 2026-04-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsconfig',
            name='ad_cooldown_seconds',
            field=models.PositiveIntegerField(default=240, help_text='Seconds between ads for the same user (default 4min)'),
        ),
        migrations.AddField(
            model_name='adsconfig',
            name='ad_every_nth_video',
            field=models.PositiveIntegerField(default=3, help_text='Show ad every N videos (e.g. 3 = every 3rd video)'),
        ),
        migrations.AddField(
            model_name='adsconfig',
            name='ads_refresh_seconds',
            field=models.PositiveIntegerField(default=300, help_text='How often the frontend re-fetches the ad pool (seconds)'),
        ),
        migrations.AlterField(
            model_name='adsconfig',
            name='ctr_estimate',
            field=models.DecimalField(decimal_places=4, default='0.0200', help_text='Estimated CTR for reach projections (0.02 = 2%)', max_digits=5),
        ),
    ]
