# Generated by Django 4.2.27 on 2026-06-16 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0042_alter_view_unique_together'),
        ('ads', '0005_adsconfig_ad_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='promoted_video',
            field=models.ForeignKey(blank=True, help_text='Video propio promocionado (boost). Null = anuncio externo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='destination_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='ads/media/'),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
