"""
Django settings for Buzzy project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import secrets
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab
load_dotenv(Path(__file__).resolve().parent.parent / ".env")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY — all sensitive values from environment only
_secret = os.getenv('SECRET_KEY')
if not _secret:
    raise RuntimeError("SECRET_KEY environment variable is required and must not be empty.")
SECRET_KEY = _secret

DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

_allowed = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
APPEND_SLASH = True


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
TRHE_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'corsheaders',
]
LOCAL_APPS = [
    'apps.users',
    'apps.videos',
    'apps.wallet',
    'apps.markerplace',
    'apps.subscriptions',
    'apps.ads',
    'apps.recommendations',
    'apps.banners',
    'apps.referrals',
]

INSTALLED_APPS  = DJANGO_APPS + TRHE_PARTY_APPS + LOCAL_APPS

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_placeholder')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_placeholder')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_placeholder')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
WEB_URL = os.getenv('WEB_URL', 'http://localhost:5173')
PLAY_STORE_URL = os.getenv('PLAY_STORE_URL', 'https://play.google.com/store/apps/details?id=com.buzzy.app')

# Social OAuth Credentials
INSTAGRAM_CLIENT_ID = os.getenv('INSTAGRAM_CLIENT_ID', '')
INSTAGRAM_CLIENT_SECRET = os.getenv('INSTAGRAM_CLIENT_SECRET', '')
TIKTOK_CLIENT_KEY = os.getenv('TIKTOK_CLIENT_KEY', '')
TIKTOK_CLIENT_SECRET = os.getenv('TIKTOK_CLIENT_SECRET', '')
FACEBOOK_APP_ID = os.getenv('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.getenv('FACEBOOK_APP_SECRET', '')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.users.middleware.UserLanguageMiddleware',
    'apps.users.rate_limit_middleware.RateLimitMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

# ── Rate limiting ──────────────────────────────────────────────────────────
# Global default: 10 requests per 10 seconds per (user/IP + path + method).
# Override per-endpoint below. window = seconds, limit = max requests.
RATE_LIMIT_ENABLED = True

RATE_LIMIT_OVERRIDES = {
    # Auth — strict: brute-force protection
    "/api/login":             {"limit": 5,  "window": 60},
    "/api/register":          {"limit": 5,  "window": 60},
    "/api/google/login":      {"limit": 5,  "window": 60},
    "/api/google/register":   {"limit": 5,  "window": 60},
    "/api/token/refresh":     {"limit": 10, "window": 60},
    # Payments — prevent double-submit
    "/api/wallet/stripe":     {"limit": 3,  "window": 30},
    "/api/ads/campaigns":     {"limit": 5,  "window": 30},
    # Social actions — generous but capped
    "/api/create-like":       {"limit": 30, "window": 10},
    "/api/create-follower":   {"limit": 20, "window": 10},
    "/api/create-comment":    {"limit": 15, "window": 10},
    # Feed — allow normal browsing
    "/api/recommendations":   {"limit": 20, "window": 10},
    "/api/list-home":         {"limit": 20, "window": 10},
}

ROOT_URLCONF = 'Buzzy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_PRIVATE_NETWORK = True

WSGI_APPLICATION = 'Buzzy.wsgi.application'

_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:5000')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(',') if o.strip()]

_csrf_env = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://localhost:5000,http://127.0.0.1:5173')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(',') if o.strip()]
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
#}

DATABASES = {
     'default': {
            'ENGINE': os.getenv('POSTGRES_ENGINE', os.getenv('DB_NAME', 'dbname')),
            'NAME': os.getenv('POSTGRES_DB', os.getenv('DB_NAME', 'dbname')),
            'USER': os.getenv('POSTGRES_USER', os.getenv('DB_USER', 'dbuser')),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', os.getenv('DB_PASSWORD', 'password')),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
     }
}


AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('JWT_ACCESS_HOURS', '24'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_SECURE = True  
SESSION_COOKIE_HTTPONLY = True  
CSRF_COOKIE_SECURE = True  
CSRF_COOKIE_HTTPONLY = True  


FASTAPI_WS_URL = os.getenv("FASTAPI_WS_URL", "http://localhost:8001")
SOCKET_URL = FASTAPI_WS_URL
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
# Shared secret used by Django → FastAPI internal broadcast calls
BROADCAST_SECRET = os.getenv("BROADCAST_SECRET", "")

GOOGLE_API_KEY=os.getenv("GOOGLE_API_KEY", "")

# xAI Grok Imagine — generación de imágenes y videos
XAI_API_KEY = os.getenv("XAI_API_KEY", "")
AI_DRY_RUN = os.getenv("AI_DRY_RUN", "false").lower() == "true"

# BytePlus (legacy — ya no se usa, se mantiene por si acaso)
BYTEPLUS_ACCESS_KEY = os.getenv("BYTEPLUS_ACCESS_KEY", "")
BYTEPLUS_SECRET_KEY = os.getenv("BYTEPLUS_SECRET_KEY", "")
BYTEPLUS_REGION     = os.getenv("BYTEPLUS_REGION", "ap-singapore-1")


AGORA_APP_ID = os.getenv("AGORA_APP_ID", "")
AGORA_APP_CERTIFICATE = os.getenv("AGORA_APP_CERTIFICATE", "")
AGORA_CUSTOMER_ID = os.getenv("AGORA_CUSTOMER_ID", "")
AGORA_CUSTOMER_SECRET = os.getenv("AGORA_CUSTOMER_SECRET", "")
AGORA_WEBHOOK_SECRET = os.getenv("AGORA_WEBHOOK_SECRET", "")
FIREBASE_SERVER_KEY = os.getenv("FIREBASE_SERVER_KEY", "")
FIREBASE_SERVICE_ACCOUNT_PATH = os.getenv("FIREBASE_SERVICE_ACCOUNT_PATH", "")

# Security headers — active in production (DEBUG=False), disabled in local dev
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
if not DEBUG:
    # En producción, SSL redirect activo por defecto. Deshabilitar solo si el proxy ya lo hace.
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1')
    # HSTS: 1 año por defecto en producción (31536000 segundos)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Celery Configuration
# 1. Definimos la URL base de Redis (puedes usar la misma para caché y Celery)
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/1')

# 2. Configuración de Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Asegúrate de que TIME_ZONE esté definido antes de esta línea en tu settings.py
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'expire-campaigns-every-15min': {
        'task': 'apps.ads.tasks.expire_campaigns',
        'schedule': crontab(minute='*/15'),
    },
    # Snapshot de vistas monetizables nuevas — corre cada noche a las 23:50
    'snapshot-monetizable-views-nightly': {
        'task': 'wallet.snapshot_monetizable_views',
        'schedule': crontab(hour=23, minute=50),
    },
    # Liquidación semanal — cada lunes a las 02:00 AM
    'settle-weekly-earnings-monday': {
        'task': 'wallet.settle_weekly_earnings',
        'schedule': crontab(hour=2, minute=0, day_of_week=1),
    },
    # Refresco de seguidores en redes sociales — cada domingo a las 03:00 AM
    'refresh-social-followers-weekly': {
        'task': 'apps.users.tasks.refresh_all_social_followers',
        'schedule': crontab(hour=3, minute=0, day_of_week=0),
    },
    # Elimina regalos no abiertos después de 30 días — cada noche a las 12:00 AM
    'expire-unopened-gifts-nightly': {
        'task': 'apps.videos.tasks.expire_unopened_gifts',
        'schedule': crontab(hour=0, minute=0),
    },
    # Banners: sincroniza grupos automáticos cada hora
    'banners-sync-groups-hourly': {
        'task': 'banners.sync_groups',
        'schedule': crontab(minute=0),
    },
    # Banners: desactiva banners expirados cada 15 minutos
    'banners-expire-every-15min': {
        'task': 'banners.expire_banners',
        'schedule': crontab(minute='*/15'),
    },
    # Banners: limpieza mensual de BannerView de banners inactivos
    'banners-cleanup-views-monthly': {
        'task': 'banners.cleanup_old_views',
        'schedule': crontab(hour=4, minute=0, day_of_month=1),
    },
    # Referidos: elimina tokens de un solo uso no usados que ya expiraron (cada hora)
    'referrals-delete-expired-tokens-hourly': {
        'task': 'referrals.delete_expired_tokens',
        'schedule': crontab(minute=0),
    },
}

# Opcional: Configuración para django-redis (si lo instalaste para el motor de recomendaciones)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL', 'redis://localhost:6379/0'), # Base 0 para caché
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
