# Generated by Django 4.2.19 on 2026-03-04 20:55

from django.db import migrations


def initialize_wallets(apps, schema_editor):
    User = apps.get_model('users', 'User')
    WalletModel = apps.get_model('wallet', 'WalletModel')
    CurrencyModel = apps.get_model('wallet', 'CurrencyModel')

    # Get or create default currency
    currency, _ = CurrencyModel.objects.get_or_create(
        code='USD',
        defaults={'name': 'US Dollar', 'symbol': '$', 'type': 'fiat'}
    )

    for user in User.objects.all():
        if not WalletModel.objects.filter(user=user).exists():
            WalletModel.objects.create(
                user=user,
                balance=100.00,
                currency=currency,
                wallet_type='main'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('users', '0001_initial'), # Ensure users table exists
    ]

    operations = [
        migrations.RunPython(initialize_wallets),
    ]
