# Generated by Django 4.2.27 on 2026-04-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_add_monetizable_views_to_videostats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='view_rate_per_1000',
            field=models.DecimalField(decimal_places=4, default='0.1000', help_text='USD que se paga al creador por cada 1,000 vistas monetizables.', max_digits=8),
        ),
        migrations.CreateModel(
            name='VideoEarningsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views_delta', models.PositiveIntegerField(default=0)),
                ('already_settled', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_earnings_daily', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_daily', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Earnings Daily',
                'verbose_name_plural': 'Video Earnings Daily',
                'unique_together': {('video', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CreatorEarningsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('monetizable_views', models.PositiveIntegerField(default=0)),
                ('rate_per_1000', models.DecimalField(decimal_places=4, max_digits=8)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('rejected', 'Rechazado')], default='pending', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Earnings Period',
                'verbose_name_plural': 'Creator Earnings Periods',
                'ordering': ['-week_start'],
                'unique_together': {('creator', 'week_start')},
            },
        ),
    ]
