# Generated by Django 5.1.6 on 2025-11-15 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletmodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='walletmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='blocked_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='currency',
            field=models.CharField(default='DOP', max_length=5),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='last_transaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='total_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main Wallet'), ('bonus', 'Bonus Wallet'), ('points', 'Points Wallet')], default='main', max_length=10),
        ),
    ]
