# Generated by Django 4.2.27 on 2026-04-26 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_add_monetizable_views_to_videostats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_add_view_rate_and_earnings_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoearningsdaily',
            name='last_snapshot_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonetizableViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monetizable_view_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monetizable_view_logs', to='videos.video')),
            ],
            options={
                'verbose_name': 'Monetizable View Log',
                'verbose_name_plural': 'Monetizable View Logs',
                'unique_together': {('user', 'video', 'date')},
            },
        ),
    ]
