# Generated by Django 5.1.6 on 2025-11-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_walletmodel_amount_remove_walletmodel_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('fiat', 'Fiat Currency'), ('crypto', 'Cryptocurrency')], default='fiat', max_length=10)),
                ('decimals', models.IntegerField(default=2)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
