# Generated by Django 4.2.27 on 2026-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_initialize_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
