# Generated by Django 5.1.6 on 2025-11-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_currencymodel_alter_walletmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='wallet.currencymodel'),
        ),
    ]
