# Generated by Django 4.2.19 on 2026-03-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletmodel_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10),
        ),
    ]
