# Generated by Django 5.1.6 on 2025-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_walletmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='pass_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
