# Generated by Django 4.2.27 on 2026-06-11 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_globalsettings_gift_fee_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('follower_threshold', models.PositiveIntegerField(help_text='N: seguidores requeridos para ganar.')),
                ('capacity', models.PositiveIntegerField(help_text='X: cupo de ganadores. Al llenarse, cierra.')),
                ('duration_months', models.PositiveIntegerField(default=3, help_text='D: meses que dura el bono por ganador.')),
                ('gift_fee_pct', models.DecimalField(decimal_places=2, default=30.0, help_text='Comisión de regalos para los ganadores (reemplaza la global).', max_digits=5)),
                ('view_rate_per_1000', models.DecimalField(decimal_places=4, default='0.1000', help_text='USD por 1000 vistas para los ganadores (reemplaza la global).', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bonus Campaign',
                'verbose_name_plural': 'Bonus Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('gift_fee_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('view_rate_per_1000', models.DecimalField(decimal_places=4, max_digits=8)),
                ('follower_count_at_win', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='wallet.bonuscampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Bonus',
                'verbose_name_plural': 'Creator Bonuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='wallet_crea_user_id_796431_idx')],
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
