# Generated by Django 4.2.19 on 2026-03-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.bankaccount'),
        ),
    ]
