# Generated by Django 5.1.6 on 2025-11-16 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='pass_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
