# Generated by Django 4.2.19 on 2026-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_tokenpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_token_price_usd', models.DecimalField(decimal_places=4, default=0.015, help_text='Precio en USD por cada token en recargas personalizadas.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
    ]
