# Generated by Django 5.1.6 on 2025-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_walletmodel_pass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='pass_code',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
