# Generated by Django 4.2.27 on 2026-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
