# Generated by Django 5.1.6 on 2025-11-16 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_walletmodel_pass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='pass_code',
            field=models.CharField(default=uuid.uuid4, max_length=18, unique=True),
        ),
    ]
