# Generated by Django 4.2.27 on 2026-04-29 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_auto', models.BooleanField(default=True, help_text='Si es True, se sincroniza automáticamente por requisitos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de usuarios',
                'verbose_name_plural': 'Grupos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='GroupRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('has_subscription', 'Tiene suscripción activa'), ('subscription_plan', 'Plan de suscripción'), ('followers_count', 'Cantidad de seguidores'), ('following_count', 'Cantidad de seguidos'), ('account_age_days', 'Días desde registro'), ('total_videos', 'Videos publicados'), ('is_buzzy_premium', 'Tiene Buzzy Premium'), ('country', 'País'), ('total_tokens', 'Tokens en wallet'), ('videos_this_month', 'Videos este mes')], max_length=50)),
                ('operator', models.CharField(choices=[('eq', 'Igual a'), ('gt', 'Mayor que'), ('lt', 'Menor que'), ('gte', 'Mayor o igual'), ('lte', 'Menor o igual'), ('in', 'Está en lista (separar por comas)')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='banners.usergroup')),
            ],
            options={
                'verbose_name': 'Requisito de grupo',
                'verbose_name_plural': 'Requisitos de grupo',
            },
        ),
        migrations.CreateModel(
            name='BuzzyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ANNOUNCEMENT', 'Anuncio'), ('ALERT', 'Alerta'), ('ACHIEVEMENT', 'Logro'), ('PRIZE', 'Premio'), ('OFFER', 'Oferta')], default='ANNOUNCEMENT', max_length=20)),
                ('effect', models.CharField(choices=[('PARTICLES', 'Partículas'), ('HOLOGRAPHIC', 'Holográfico'), ('SCRATCH', 'Rasca y Revela'), ('NARRATIVE', 'Narrativo'), ('COUNTDOWN', 'Cuenta Regresiva'), ('NONE', 'Sin efecto')], default='NONE', max_length=20)),
                ('target', models.CharField(choices=[('GLOBAL', 'Global — todos los usuarios'), ('PERSONAL', 'Personal — un usuario'), ('GROUP', 'Grupo — grupo de usuarios')], default='GLOBAL', max_length=10)),
                ('background_color', models.CharField(default='#7C3AED', max_length=50)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('accent_color', models.CharField(default='#A78BFA', max_length=50)),
                ('reveal_content', models.TextField(blank=True, help_text='Texto que se revela al rascar (SCRATCH)')),
                ('countdown_label', models.CharField(blank=True, help_text='Label del contador (COUNTDOWN)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.usergroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Buzzy',
                'verbose_name_plural': 'Banners Buzzy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='banners.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de grupo',
                'verbose_name_plural': 'Membresías de grupo',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='BannerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='banners.buzzybanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista de banner',
                'verbose_name_plural': 'Vistas de banner',
                'unique_together': {('user', 'banner')},
            },
        ),
    ]
