# Generated by Django 4.2.27 on 2026-05-20 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buzzybanner',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Banner Buzzy', 'verbose_name_plural': 'Banners Buzzy'},
        ),
        migrations.AddField(
            model_name='buzzybanner',
            name='action_label',
            field=models.CharField(blank=True, help_text='Texto del botón CTA ej: Ver oferta', max_length=80),
        ),
        migrations.AddField(
            model_name='buzzybanner',
            name='action_url',
            field=models.CharField(blank=True, help_text='Ruta interna de la app ej: /wallet, /profile/123', max_length=500),
        ),
        migrations.AddField(
            model_name='buzzybanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen decorativa opcional', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='buzzybanner',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Mayor número = mayor prioridad dentro del mismo target'),
        ),
        migrations.CreateModel(
            name='BannerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Vista'), ('click', 'Click en CTA'), ('dismiss', 'Descartado'), ('scratch', 'Rascado completo'), ('expired', 'Expiró automáticamente')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='banners.buzzybanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de banner',
                'verbose_name_plural': 'Interacciones de banner',
                'indexes': [models.Index(fields=['banner', 'action'], name='banners_ban_banner__df749a_idx'), models.Index(fields=['user', 'created_at'], name='banners_ban_user_id_9fa591_idx')],
            },
        ),
    ]
